# Generated by Django 5.1.6 on 2025-03-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_task_completed_task_completed_at_task_rejected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_completed', 'Задача выполнена'), ('task_assigned', 'Задача назначена'), ('task_rejected', 'Задача отклонена')], max_length=20),
        ),
    ]
